(function(){var b;b=function(){function b(c,a){var f,d;null==a&&(a={});this.h=this.l=!1;f=[];document.getElementById(c)||f.push("ID must be a valid DOM Element");/^[0-9a-fA-F]{24}$/.test(a.id)||this.j(a.id)||f.push("Options.id must be a valid Platform Video ID or a YouTube Video ID");"media"!==(d=a.type)&&"live"!==d&&"dvr"!==d&&f.push('Options.type must be "media", "live" or "dvr"');isNaN(parseInt(a.width))&&f.push("Options.width must be a positive integer");isNaN(parseInt(a.height))&&f.push("Options.height must be a positive integer");
0<f.length?this.m(f):this.G(c,a)}b.prototype.G=function(c,a){var b,d,e,g,l,h,m,n,p,k;this.i={};this.F(function(a){return function(){return a.H(arguments)}}(this));this.b={};"function"===typeof(null!=(d=a.events)?d.onPlayerReady:void 0)&&(this.b.v=function(){return function(){return a.events.onPlayerReady}}(this));"function"===typeof(null!=(e=a.events)?e.onVideoEnd:void 0)&&(this.b.w=function(){return function(){return a.events.onVideoEnd}}(this));"function"===typeof(null!=(l=a.events)?l.onVideoStop:
void 0)&&(this.b.B=function(){return function(){return a.events.onVideoStop}}(this));"function"===typeof(null!=(h=a.events)?h.onVideoError:void 0)&&(this.b.A=function(){return function(){return a.events.onVideoError}}(this));"function"===typeof(null!=(m=a.events)?m.onVolumeChange:void 0)&&(this.b.C=function(){return function(){return a.events.onVolumeChange}}(this));"function"===typeof(null!=(n=a.events)?n.onPlay:void 0)&&(this.b.u=function(){return function(){return a.events.onPlay}}(this));this.a=
[];this.a.push("jsapi=true");null!=a.pause_ad_on_click&&this.a.push("pause_ad_on_click="+encodeURIComponent(a.pause_ad_on_click));null!=a.autoplay&&this.a.push("autoplay="+encodeURIComponent(a.autoplay));null!=a.controls&&this.a.push("controls="+encodeURIComponent(a.controls));null!=a.volume&&this.a.push("volume="+encodeURIComponent(a.volume));a.player&&this.a.push("player="+encodeURIComponent(a.player));a.skin&&this.a.push("skin="+encodeURIComponent(a.skin));a.ref&&this.a.push("ref="+encodeURIComponent(a.ref));
null!=a.startTime&&this.a.push("starttime="+encodeURIComponent(a.startTime));null!=a.endTime&&this.a.push("endtime="+encodeURIComponent(a.endTime));null!=a.title&&this.a.push("title="+encodeURIComponent(a.title));null!=a.show_title&&this.a.push("show_title="+encodeURIComponent(a.show_title));null!=a.access_token&&this.a.push("access_token="+encodeURIComponent(a.access_token));null!=a.admin_token&&this.a.push("admin_token="+encodeURIComponent(a.admin_token));null!=a.source&&this.a.push("source="+encodeURIComponent(a.source));
null!=a.customer&&this.a.push("c="+encodeURIComponent(a.customer));null!=a.rendition_rule&&this.a.push("rendition_rule="+encodeURIComponent(a.rendition_rule));null!=a.dnt&&this.a.push("dnt="+encodeURIComponent(a.dnt));null!=(null!=(p=a.style)?p.basecolor:void 0)&&this.a.push("style[basecolor]="+encodeURIComponent(a.style.basecolor));null!=(null!=(k=a.style)?k.backgroundcolor:void 0)&&this.a.push("style[backgroundcolor]="+encodeURIComponent(a.style.backgroundcolor));!0===a.mse&&this.a.push("mse=true");
!0===a.rtsp&&this.a.push("rtsp=true");!0===a.debug&&this.a.push("debug=true");!0===a.no_ad&&this.a.push("no_ad=true");e=a.ads||{};for(b in e)d=e[b],this.a.push("ads["+b+"]="+encodeURIComponent(d));e=a.custom||{};for(b in e)d=e[b],this.a.push("custom."+b+"="+encodeURIComponent(d));this.g=[];this.g.push(""+this.protocol()+"//"+(window.EMBED_HOST||"mdstrm.com")+"/");this.g.push("live"===(g=a.type)||"dvr"===g?"live-stream":"embed");this.g.push("/");this.j(a.id)&&this.g.push("y/");this.g.push(this.j(a.id)||
a.id);this.g.push("?");this.g.push(this.a.join("&"));this.o=document.getElementById(c);this.f=document.createElement("IFRAME");this.f.src=this.g.join("");this.f.width=parseInt(a.width);this.f.height=parseInt(a.height);this.f.frameBorder=0;this.f.setAttribute("allowfullscreen","");this.f.setAttribute("allowscriptaccess","always");this.o.innerHTML="";this.o.appendChild(this.f);this.D=this.f.contentWindow};b.prototype.protocol=function(){return/^http/i.test(location.protocol)?location.protocol:"https:"};
b.prototype.F=function(c){var a=window;null!=a&&(a.addEventListener?a.addEventListener("message",c,!1):a.attachEvent("onmessage",c))};b.prototype.H=function(){var c,a,b,d,e,g,l,h,m,n,p,k,u,q,v,r,w,t,x;c=null!=arguments?null!=(d=arguments[0])?d[0]:void 0:void 0;switch(null!=c?null!=(e=c.data)?e.eventName:void 0:void 0){case "onPlayerReady":return this.l=!0,null!=(k=this.b)?"function"===typeof k.v?k.v().apply(this,[null!=(u=c.data.eventData)?u:{}]):void 0:void 0;case "onVideoEnd":return this.h=!1,null!=
(q=this.b)?"function"===typeof q.w?q.w().apply(this,[null!=(v=c.data.eventData)?v:{}]):void 0:void 0;case "onVideoStop":return this.h=!1,null!=(r=this.b)?"function"===typeof r.B?r.B().apply(this,[null!=(w=c.data.eventData)?w:{}]):void 0:void 0;case "onVideoError":return this.h=!1,null!=(t=this.b)?"function"===typeof t.A?t.A().apply(this,[null!=(x=c.data.eventData)?x:{}]):void 0:void 0;case "onVolumeChange":return null!=(g=this.b)?"function"===typeof g.C?g.C().apply(this,[null!=(l=c.data.eventData)?
l:{}]):void 0:void 0;case "onPlay":return this.h=!0,null!=(h=this.b)?"function"===typeof h.u?h.u().apply(this,[null!=(m=c.data.eventData)?m:{}]):void 0:void 0;default:return"function"===typeof(a=this.i)[b=null!=c?null!=(n=c.data)?n.eventName:void 0:void 0]?a[b](null!=(p=c.data.eventData)?p:null):void 0}};b.prototype.s=function(c){var a;return this.l?null!=(a=this.D)?a.postMessage(c,""+this.protocol()+"//"+(window.EMBED_HOST||"mdstrm.com")):void 0:this.m(["Player is not ready yet, please wait for the onPlayerReady event"])};
b.prototype.c=function(c,a){for(var b;null==b||null!=this.i[b];)b=Math.random().toString(32).substr(2);this.i[b]=function(c){return function(){"function"===typeof a&&a.apply(null,arguments);return delete c.i[b]}}(this);return this.s({cb:b,eventName:c.action||c,data:c.data})};b.prototype.j=function(b){var a;null==b&&(b="");return null!=(a=b.match(/^youtube:(.+)/i))?a[1]:void 0};b.prototype.m=function(b){null==b&&(b=[]);return"undefined"!==typeof console&&null!==console?console.error("[MDSTRM.Player] "+
b.join(". ")):void 0};b.prototype.N=function(){return this.l};b.prototype.M=function(){return this.h};b.prototype.O=function(b){return b?(this.s({action:"requestAds",data:b}),!0):!1};b.prototype.P=function(b,a){null==b&&(b=0);null==a&&(a=function(){});return this.c({action:"seekTo",data:b},a)};b.prototype.T=function(b){null==b&&(b=function(){});return this.c("videoPlay",b)};b.prototype.U=function(b){null==b&&(b=function(){});return this.c("videoStop",b)};b.prototype.I=function(b){return this.c("getCurrentTime",
b)};b.prototype.L=function(b){return this.c("getVideoMetrics",b)};b.prototype.S=function(b,a){null==a&&(a=function(){});return this.c({action:"setVolume",data:b},a)};b.prototype.R=function(b,a){null==a&&(a=function(){});return this.c({action:"setAdsVolume",data:b},a)};b.prototype.J=function(b){return this.c("getDuration",b)};b.prototype.K=function(b,a,f){return this.c({action:"getSnapshot",data:{height:a,width:b}},f)};return b}();window.MediastreamPlayer=b;b.prototype.isReady=b.prototype.N;b.prototype.isPlaying=
b.prototype.M;b.prototype.requestAds=b.prototype.O;b.prototype.seekTo=b.prototype.P;b.prototype.videoPlay=b.prototype.T;b.prototype.videoStop=b.prototype.U;b.prototype.getCurrentTime=b.prototype.I;b.prototype.getVideoMetrics=b.prototype.L;b.prototype.setVolume=b.prototype.S;b.prototype.setAdsVolume=b.prototype.R;b.prototype.getDuration=b.prototype.J;b.prototype.getSnapshot=b.prototype.K}).call(this);
